#!/usr/bin/env bash

set -eou pipefail

if [[ $# -gt 1 ]]; then
  echo -e "\e[1;31mInvalid number of arguments\e[0m"
  echo -e "\e[1;32mUsage: bash $0 --build\e[0m"
  exit 1
fi

arg=""
if [[ $# -eq 1 && $1 != "--build" ]]; then
  echo -e "\e[1;31mInvalid argument\e[0m"
  echo -e "\e[1;32mUsage: bash $0 --build\e[0m"
  exit 1
elif [[ $# -eq 1 && $1 == "--build" ]]; then
  arg=$1
fi

if [[ $arg == "--build" ]]; then
  echo -e "\e[1;32mBuilding the project and running test\e[0m"
  npm run build
else
  echo -e "\e[1;32mRunning test\e[0m"
fi

node dist/index.js &
node_pid=$!

while ! nc -z localhost "$PORT"; do
  echo "Waiting for server to start..."
  sleep 0.1
done

playwright_test_exit_code=1

if npx playwright test; then
  playwright_test_exit_code=0
fi

node tests/cleanup.js
echo "Stopping server..."
kill $node_pid

if [[ $playwright_test_exit_code -eq 0 ]]; then
  echo -e "\e[1;32mTests passed\e[0m"
else
  echo -e "\e[1;31mTests failed\e[0m"
  exit 1
fi
