#!/usr/bin/env bash

set -eou pipefail

export MONGO_INITDB_USERNAME=test-user
export MONGO_INITDB_PASSWORD=oNVnSwoivIxQss5c
export MONGO_CLUSTER=cluster0.hhxxk.mongodb.net
export PORT=3100
export MONGO_INITDB_DATABASE=rest-api-test


npm run build
node dist/index.js &
node_pid=$!

while ! nc -z localhost $PORT; do
  echo "Waiting for server to start..."
  sleep 0.1
done

if npx playwright test; then
  echo "Tests passed"
  node tests/cleanup.js
  kill $node_pid
fi

