#!/usr/bin/env bash

set -eou pipefail

export MONGO_INITDB_USERNAME=test-user
export MONGO_INITDB_PASSWORD=oNVnSwoivIxQss5c
export MONGO_CLUSTER=cluster0.hhxxk.mongodb.net
export PORT=3100
export MONGO_INITDB_DATABASE=rest-api-test

if [[ $# -gt 1 ]]; then
  echo -e "\e[1;31mInvalid number of arguments\e[0m"
  echo -e "\e[1;32mUsage: bash $0 --build\e[0m"
  exit 1
fi

arg=""
if [[ $# -eq 1 && $1 != "--build" ]]; then
  echo -e "\e[1;31mInvalid argument\e[0m"
  echo -e "\e[1;32mUsage: bash $0 --build\e[0m"
  exit 1
elif [[ $# -eq 1 && $1 == "--build" ]]; then
  arg=$1
fi

if [[ $arg == "--build" ]]; then
  echo -e "\e[1;32mBuilding the project and running test\e[0m"
  npm run build
else
  echo -e "\e[1;32mRunning test\e[0m"
fi

node dist/index.js &
node_pid=$!

while ! nc -z localhost $PORT; do
  echo "Waiting for server to start..."
  sleep 0.1
done

if npx playwright test; then
  echo "Tests passed"
  node tests/cleanup.js
  kill $node_pid
fi

