name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  pre: 'setup.js'
  main: 'dist/index.js'