name: Using Docker action
on: workflow_dispatch

jobs:
  docker-job:
    runs-on: ubuntu-latest
    name: A docker example
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        path: project
#      - name: Build local actions
#        shell: bash
#        run: |
#          bash .github/actions/build-actions
      - name: Copy project to action directory
        run: |
          cp -rf ./project/** .github/actions/docker-action
      - name: Docker action step
        id: hello
        uses: ./.github/actions/docker-action
        with:
          who-to-greet: 'Jorgeeeeeasdasd'
#      - name: Get the output time
#        run: echo "The time was ${{ steps.hello.outputs.time }}"
#      - name: Env vars
#        run: |
#          env