name: Using Javascript action
on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build actions
        shell: bash
        run: |
          bash ./.github/actions/build-actions
      - name: Hello world action step
        id: hello
        uses: ./.github/actions/deploy-s3-js-action
        with:
          who-to-greet: 'Jorgeeeee'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"