name: Matrix Demo
on:
  push:
    branches:
      - master
defaults:
  run:
    shell: bash
    working-directory: project
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - node-version: [18.x]
            os: [ubuntu-latest]
        exclude:
          - node-version: [12.x]
            os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
        - name: Getting Code in os ${{ matrix.os }} and node ${{ matrix.node-version }}
          uses: actions/checkout@v3
        - name: Setting up Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        - name: Install dependencies
          run: npm ci
        - name: Linting
          run: npm run lint
        - name: Build
          run: npm run build

