name: Script Injection
# on open an issue
on:
  issues:
    types: [opened]
# #          issue_title="${{ github.event.issue.title }}"
jobs:
  inject:
    runs-on: ubuntu-latest
    steps:
      - name: Inject
        run: |
          echo "$GITHUB_EVENT_PATH"
          echo "${{ toJSON(github.event.issue) }}"
          issue_title=$(jq --raw-output .issue.title "$GITHUB_EVENT_PATH")
          issue_title_escape_any_html_chars=$(echo "$issue_title" | sed 's/</\&lt;/g' | sed 's/>/\&gt;/g')
          echo "issue_title_escape_any_html_chars: $issue_title_allow_script_injection"
          issue_title="${{ github.event.issue.title }}"
          echo "issue_title: $issue_title"
