name: Script Injection
# on open an issue
on:
  issues:
    types: [opened]
jobs:
  inject:
    runs-on: ubuntu-latest
    steps:
      - name: Inject
        run: |
          echo "$GITHUB_EVENT_PATH"
          echo "${{ github.event.issue }}"
          issue_number=$(jq --raw-output .issue.number "$GITHUB_EVENT_PATH")
          echo "issue_number=$issue_number"
