name: Test rest api with composite custom actions
on: workflow_dispatch
jobs:
  deploy:
    environment: production
    uses: ./.github/workflows/deploy-serverless.yml
    with:
      stage: production
