name: Test
on: workflow_dispatch
jobs:
  deploy:
    uses: ./.github/workflows/deploy-serverless.yml
    secrets: inherit
#      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
    with:
      stage: production
